server:
  port: 8084
#  servlet:
#      context-path: /security
spring:
    datasource:
        name: pis
        url: jdbc:mysql://114.116.154.251:3306/pis?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
#         使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
    freemarker:
      template-loader-path: classpath:/templates/
      suffix: .html
      content-type: text/html
      charset: UTF-8

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update




## 该配置节点为独立的节点
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml  # 注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.lc.websocket.bean # 注意：对应实体类的路径
  config-location: classpath:mybatis/mybatis-config.xml


